_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 2
                - 3
                - 41
                - 55
            "2":
                - 1
                - 2
                - 3
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 128
epochs:
    value: 200
learning_rate:
    value: 0.1
net:
    value: resnet18
optimizer:
    value: SGD
warmup_epochs:
    value: 1
